@startuml
skinparam sequence {
	GroupBackgroundColor #ff8888
}
== Initialization ==
participant Factory
actor Client #red
Client-->Factory:use
create Formatter
Factory->Formatter:for instantiation
Formatter->Client:got *Formatter reference
activate Client
box "Another threads" #lightblue
actor Second #lightgreen
actor Third #lightgreen
end box
note over Second, Third
 Second and Third classes
 have no idea about Factory
 they got preinstantiated 
 formatter from Client
endnote
Second<--Client:put *Formatter reference
activate Second
Third<--Client:put *Formatter reference
activate Third
... ~~some possible delay~~ ...
== Concurrent Access ==
group Here we have troubles
Client -[#red]> Formatter:parse()
activate Formatter #ee6644
Second -[#red]> Formatter:format()
Client -[#red]> Formatter:format()
Third -[#red]> Formatter:parse()
Second -[#red]> Formatter:format()
Client -[#red]> Formatter:parse()
Third -[#red]> Formatter:parse()
end
@enduml